"""Copy pass: Gen-Z Egyptian Arabic + punchy streetwear English. Only customer-facing strings change;
keys, placeholders ({{ x }}) and HTML wrappers are preserved."""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2] / "theme"

AR = {
    "general.error": "حصل خطأ صغير. جرّب تاني.",
    "general.copied": "اللينك اتنسخ ✓",
    "general.whatsapp": "كلّمنا واتساب",
    "general.whatsapp_prefill": "هاي LINUX 👋 عندي سؤال عن",
    "general.view_all": "شوف الكل",
    "general.back_home": "ارجع للرئيسية",
    "general.loading": "ثواني…",
    "nav.shop": "تسوّق",
    "nav.saved": "المحفوظات",
    "nav.bag": "الشنطة",
    "sections.hero.eyebrow": "LINUX · القاهرة · FW26",
    "sections.hero.heading": "اتطرّز في القاهرة. اتلبس في كل حتة.",
    "sections.hero.subheading": "ستريت وير تقيل ومطرّز — مش مطبوع.",
    "sections.hero.cta": "شوف الدروب",
    "sections.hero.cta2": "اعمل بتاعك",
    "sections.hero.trust_1": "شحن ببلاش فوق 2,000 جنيه",
    "sections.hero.trust_2": "استبدال خلال 14 يوم من غير وجع دماغ",
    "sections.hero.trust_3": "تطريز حقيقي، مش طباعة",
    "newsletter.footer_label": "أول ما فيه دروب جديد، هتعرف قبل الكل — وخصم 10% على أول أوردر.",
    "newsletter.placeholder": "إيميلك",
    "newsletter.button": "دخّلني",
    "newsletter.success": "تمام، بقيت من الفلوك 🐧",
    "password.title": "في حاجة بتتطرّز دلوقتي.",
    "password.body": "دروب LINUX الجديد على وصول. سيب إيميلك وهتدخل قبل الكل.",
    "search.placeholder": "بتدوّر على إيه؟ هودي، تيشيرت…",
    "search.popular": "الناس بتدوّر على",
    "search.no_results": "مفيش نتايج. جرّب كلمة تانية.",
    "search.empty_title": "مفيش حاجة هنا",
    "search.empty_body": "غيّر الكلمة أو اتفرّج على الدروب الجديد.",
    "wishlist.title": "المحفوظات",
    "wishlist.saved": "اتحفظت ♥",
    "wishlist.removed": "اتشالت من المحفوظات",
    "wishlist.empty_title": "لسه محفظتش حاجة",
    "wishlist.empty_body": "دوس على القلب على أي قطعة وهتلاقيها هنا.",
    "collections.filter": "فلتر",
    "collections.sort": "رتّب",
    "collections.clear": "امسح الكل",
    "collections.apply": "وريني النتايج",
    "collections.in_stock": "المتاح بس",
    "collections.empty": "مفيش قطع بالفلاتر دي. وسّعها شوية.",
    "products.new": "جديد",
    "products.from": "من",
    "products.quick_add": "ضيف بسرعة",
    "products.quick_view": "شوف بسرعة",
    "products.add_to_bag": "ضيف للشنطة",
    "products.notify_me": "قولّي لما يرجع",
    "products.choose_size": "اختار مقاسك",
    "products.size_guide": "دليل المقاسات",
    "products.description": "التفاصيل",
    "products.fabric": "الخامة والعناية",
    "products.shipping": "الشحن والاستبدال",
    "products.free_shipping_over": "شحن ببلاش فوق {{ amount }}",
    "products.shipping_body": "<p>شحن ببلاش فوق 2,000 جنيه. ادفع لما توصلك في أي حتة في مصر. استبدال خلال 14 يوم لو القطعة زي ما هي وبالتيكت.</p>",
    "products.fabric_body": "<p>قطن ميلتون تقيل 340 جرام. تطريز مش طباعة. اغسله بارد ومقلوب. مجفف لا.</p>",
    "products.low_stock": "فاضل {{ count }} بس 👀",
    "products.in_stock": "متاح",
    "products.you_may_like": "كمّل اللوك",
    "products.recently_viewed": "شفته قبل كده",
    "products.share": "شير القطعة",
    "products.view_full": "التفاصيل كلها",
    "products.select_size": "اختار مقاس",
    "products.embroidered": "متطرّز في القاهرة",
    "products.true_to_size": "قصّة أوفرسايز — لو بين مقاسين انزل مقاس",
    "size_guide.intro": "المقاسات بالسنتي والقطعة مفرودة. القصّة أوفرسايز.",
    "size_guide.tip": "بين مقاسين؟ انزل مقاس لو عايزها مضبوطة، أو اطلع مقاس لو عايزها واسعة.",
    "cart.title": "شنطتك",
    "cart.added": "اتضافت للشنطة",
    "cart.view_bag": "شوف الشنطة",
    "cart.checkout": "كمّل الطلب",
    "cart.subtotal": "الإجمالي",
    "cart.shipping_note": "الشحن بيتحسب في الخطوة الجاية.",
    "cart.remove": "شيل",
    "cart.empty_title": "شنطتك فاضية",
    "cart.empty_body": "لسه مفيش حاجة متطرّزة. ابدأ بالدروب الجديد.",
    "cart.start_shopping": "يلا نتسوّق",
    "cart.add_note": "ضيف ملاحظة",
    "cart.note_placeholder": "رسالة هدية، تفاصيل التوصيل…",
    "cart.upsell_title": "كمّل اللوك",
    "cart.free_shipping_unlocked": "الشحن بقى ببلاش 🎉",
    "cart.free_shipping_away": "فاضل {{ amount }} والشحن يبقى ببلاش",
    "cart.free_shipping_away_html": "فاضل <strong>{{ amount }}</strong> والشحن يبقى ببلاش",
    "cart.continue": "كمّل تسوّق",
    "cart.discount_code": "كود خصم",
    "cart.discount_placeholder": "اكتب الكود هنا",
    "cart.apply_discount": "فعّل",
    "cart.discount_hint": "الكود بيتفعّل في الخطوة الجاية.",
    "customize.title": "استوديو التخصيص",
    "customize.subtitle": "ارفع تصميمك، اختار القطعة واللون، وشوفه عليها لايف.",
    "customize.upload": "ارفع تصميمك",
    "customize.upload_hint": "PNG أو JPG أو SVG · لحد 10 ميجا",
    "customize.replace": "غيّر التصميم",
    "customize.remove": "شيل",
    "customize.garment": "القطعة",
    "customize.color": "اللون",
    "customize.side": "الجهة",
    "customize.front": "قدام",
    "customize.back": "ورا",
    "customize.size": "المقاس",
    "customize.position": "المكان والحجم",
    "customize.scale": "الحجم",
    "customize.method": "الطريقة",
    "customize.notes": "ملاحظات للفريق",
    "customize.notes_placeholder": "لون الخيط، مكان معيّن، أي تفاصيل…",
    "customize.total": "الإجمالي",
    "customize.add": "ضيف للشنطة",
    "customize.need_design": "ارفع تصميم الأول",
    "customize.need_size": "اختار مقاس",
    "customize.hint_3d": "اسحب التصميم على القطعة وحطّه في المكان اللي يعجبك",
    "customize.steps_title": "بتشتغل إزاي",
    "customize.step_1": "ارفع التصميم",
    "customize.step_2": "اختار القطعة واللون",
    "customize.step_3": "حدّد المكان والحجم",
    "customize.step_4": "بنطرّزها في 3–5 أيام",
    "customize.file_too_big": "الملف كبير (أقصى حاجة 10 ميجا).",
    "customize.file_type": "ارفع PNG أو JPG أو SVG.",
    "customize.reset": "رجّع المكان",
    "customize.quantity": "عدد القطع",
    "customize.sizes_title": "مقاس كل قطعة",
    "customize.piece": "قطعة {{ n }}",
    "customize.min_embroidery": "التطريز بيبدأ من 10 قطع. الطباعة من قطعة واحدة.",
    "customize.min_embroidery_short": "التطريز: أقل عدد 10 قطع",
    "customize.print_note": "الطباعة من أول قطعة ✓",
    "customize.contact": "كلّمنا الأول",
    "customize.contact_body": "مش متأكد من الملف أو الكمية؟ ابعتلنا التصميم على واتساب ونظبطها معاك.",
    "customize.per_piece": "{{ price }} / القطعة",
    "customize.pieces_total": "{{ count }} قطعة · {{ total }}",
    "customer.account.welcome": "أهلاً {{ name }} 👋",
    "customer.account.no_orders": "لسه مفيش أوردرات.",
    "customer.account.no_orders_body": "أول أوردر ليك هيبان هنا.",
    "customer.login.title": "سجّل دخول",
    "customer.login.no_account": "جديد هنا؟",
    "customer.login.create": "اعمل حساب",
    "customer.login.guest": "كمّل كضيف",
    "customer.login.recover_body": "هنبعتلك لينك على إيميلك.",
    "customer.login.recover_success": "بص على إيميلك، بعتنالك لينك.",
    "customer.register.title": "اعمل حساب",
    "customer.register.perk_1": "دفع أسرع",
    "customer.register.perk_2": "تابع أوردراتك",
    "customer.register.perk_3": "تدخل الدروب قبل الكل",
    "blog.read_more": "اقرأ",
    "blog.back": "كل المقالات",
    "contact.title": "كلّمنا",
    "contact.send": "ابعت",
    "contact.success": "وصلت — هنرد عليك خلال 24 ساعة.",
    "contact.whatsapp_title": "أسرع على واتساب",
    "contact.whatsapp_body": "أغلب الأسئلة بتتجاوب في دقايق.",
    "contact.whatsapp_cta": "افتح واتساب",
    "page_404.title": "تُهت وسط الغُرَز",
    "page_404.body": "الصفحة دي مش موجودة — بس الدروب الجديد موجود.",
    "page_404.cta": "رجّعني للدروب",
    "home.bestsellers_eyebrow": "الأكثر مبيعاً",
    "home.bestsellers_heading": "اللي الكل بيطلبه",
    "home.collections_eyebrow": "الكوليكشنز",
    "home.collections_heading": "اختار الدروب بتاعك",
    "home.collections_customize_label": "اعمل بتاعك",
    "home.collections_customize_sub": "تصميمك، خيطنا",
    "home.collections_all_label": "كل حاجة",
    "home.campaign_eyebrow": "الدروب",
    "home.campaign_heading": "الأخضر هو الأسود الجديد.",
    "home.campaign_body": "فليس تقيل بلون الغابة، تطريز كريمي، وكل حاجة دايرية. معمول لليل القاهرة.",
    "home.campaign_primary": "شوف الهوديز",
    "home.campaign_secondary": "اعمل بتاعك",
    "home.campaign_note": "كمية محدودة · FW26",
    "home.arrivals_eyebrow": "نزل جديد",
    "home.arrivals_heading": "طازة من الماكينة",
    "home.look_eyebrow": "اللوك كامل",
    "home.look_heading": "اللوك كله بضغطة",
    "home.look_body": "دوس على أي نقطة في الصورة، أو ضيف من الليستة على طول.",
    "home.prop_1_title": "توصيل سريع",
    "home.prop_1_text": "يوم–يومين في القاهرة، 2–4 أيام في باقي مصر.",
    "home.prop_2_title": "ادفع لما توصلك",
    "home.prop_2_text": "كاش عند الاستلام، أو كارت لو تحب.",
    "home.prop_3_title": "استبدال خلال 14 يوم",
    "home.prop_3_text": "المقاس مش مظبوط؟ بدّله من غير أسئلة.",
    "home.prop_4_title": "تطريز، مش طباعة",
    "home.prop_4_text": "خيط بيعيش أكتر من الترند.",
    "home.statement_eyebrow": "مين إحنا",
    "home.statement_heading_html": "<p>بطريق ماسك بخّاخة. وبراند ماسك <em>إبرة</em>.</p>",
    "home.statement_body": "LINUX براند ستريت وير من القاهرة. كل قطعة متطرّزة — مش مطبوعة — عشان اللوجو يعيش في القماش، مش عليه.",
    "home.statement_cta": "حكايتنا",
    "home.reviews_eyebrow": "الناس قالت إيه",
    "home.reviews_heading": "لبسوه وحكموا",
    "home.reviews_rating": "4.9 / 5 · أكتر من 300 أوردر",
    "home.review_1_quote": "أتقل هودي عندي والتطريز مش طبيعي. يستاهل كل جنيه.",
    "home.review_2_quote": "الاستبدال كان سهل جداً ودليل المقاسات مظبوط 100%.",
    "home.review_3_quote": "ستيكر البطريق لوحده يستاهل. والموقع شكله جامد.",
    "home.ugc_eyebrow": "الكوميونيتي",
    "home.ugc_heading": "ملبوس في الشارع",
    "home.faq_eyebrow": "أسئلة بتتكرّر",
    "home.faq_heading": "كل اللي محتاج تعرفه",
    "home.faq_body": "التوصيل والاستبدال والمقاسات في مكان واحد.",
    "home.faq_cta": "اسأل على واتساب",
    "home.faq_1_q": "التوصيل بياخد قد إيه؟",
    "home.faq_1_a": "<p>القاهرة والجيزة: يوم–يومين. باقي مصر: 2–4 أيام. الموعد بيتأكد وانت بتكمّل الطلب.</p>",
    "home.faq_2_q": "أقدر أبدّل المقاس؟",
    "home.faq_2_a": "<p>أيوه — خلال 14 يوم، لو القطعة زي ما هي وبالتيكت. ابدأ من حسابك أو على واتساب.</p>",
    "home.faq_3_q": "بتقبلوا الدفع عند الاستلام؟",
    "home.faq_3_a": "<p>أيوه، في كل مصر. وكمان كارت وميزة.</p>",
    "home.faq_4_q": "التخصيص بيشتغل إزاي؟",
    "home.faq_4_a": "<p>ارفع تصميمك في الاستوديو، اختار القطعة واللون، شوفه لايف واطلب. بنطرّزه في 3–5 أيام.</p>",
    "home.newsletter_eyebrow": "انضم للفلوك",
    "home.newsletter_heading": "تعرف بالدروب قبل الكل.",
    "home.newsletter_body": "خصم 10% على أول أوردر. من غير سبام — بطاريق بس.",
    "home.recommendations_heading": "كمّل اللوك",
    "home.footer_tagline": "ستريت وير من القاهرة. تطريز، مش طباعة. معمول يعيش أكتر من الترند.",
    "home.announcement": "شحن ببلاش فوق 2,000 جنيه · ادفع لما توصلك · استبدال خلال 14 يوم",
    "home.mega_promo": "دروب FW26",
    "home.shop_cta": "تسوّق",
    "home.customize_eyebrow": "استوديو التخصيص",
    "home.customize_heading": "تصميمك. خيطنا.",
    "home.customize_faq_title": "حاجات مهمة تعرفها",
    "home.customize_faq_1_q": "إيه أحسن نوع ملف؟",
    "home.customize_faq_1_a": "<p>PNG بدقة عالية وخلفية شفافة، أو SVG. وخلّيه أقل من 10 ميجا.</p>",
    "home.customize_faq_2_q": "كام لون خيط؟",
    "home.customize_faq_2_a": "<p>لحد 6 ألوان في التصميم. بنقرّب من ألوانك بأقصى ما الخيط يسمح.</p>",
    "home.customize_faq_3_q": "بياخد وقت قد إيه؟",
    "home.customize_faq_3_a": "<p>3–5 أيام شغل للتطريز، وبعدها التوصيل.</p>",
    "home.about_eyebrow": "حكايتنا",
    "home.about_heading": "الخيط قبل الترند.",
    "home.about_body": "LINUX براند ستريت وير من القاهرة. كل قطعة متطرّزة — مش مطبوعة — عشان اللوجو يعيش في القماش، مش عليه.",
    "home.about_moment_1_x": "اتطرّز على ماكينة مستلفة في مدينة نصر. خلص في أسبوع.",
    "home.about_moment_2_t": "البطريق وصل",
    "home.about_moment_2_x": "شخبطة على فاتورة بقت وش البراند.",
    "home.about_why_eyebrow": "ليه تطريز",
    "home.about_why_heading_html": "<p>الطباعة بتبهت. <em>الخيط</em> لا.</p>",
    "home.about_why_body": "اللوجو بتاعنا بيتخيّط بسرعة 4,000 غرزة في الدقيقة، وهيعيش أكتر من الهودي نفسه. ودي الفكرة كلها.",
    "home.contact_heading": "كلّمنا",
    "home.contact_body": "عندك سؤال عن أوردر أو مقاس أو تصميم؟ واتساب أو رسالة — بنرد في ساعات.",
    "home.contact_faq_title": "قبل ما تسأل",
    "home.marquee_1": "شحن ببلاش فوق 2,000 جنيه",
    "home.marquee_2": "تطريز، مش طباعة",
    "home.marquee_3": "استبدال خلال 14 يوم",
    "home.marquee_4": "ميلتون تقيل 340 جرام",
    "home.marquee_5": "ادفع لما توصلك",
    "bundle.title": "خد أكتر، ادفع أقل",
    "bundle.subtitle": "الخصم بيتطبّق لوحده في الشنطة.",
    "bundle.tier": "اشتري {{ count }}",
    "bundle.save": "وفّر {{ percent }}%",
    "bundle.each": "{{ price }} / القطعة",
    "bundle.add": "ضيف {{ count }} للشنطة",
    "bundle.mix": "ينفع تلخبط ألوان ومقاسات",
    "fit.title": "اعرف مقاسك",
    "fit.subtitle": "ادخل طولك ووزنك ونقولك أقرب مقاس.",
    "fit.height": "الطول (سم)",
    "fit.weight": "الوزن (كجم)",
    "fit.style": "تحب تلبسها إزاي؟",
    "fit.regular": "على المقاس",
    "fit.oversized": "أوفرسايز",
    "fit.result": "على الأغلب مقاسك",
    "fit.result_alt": "أو {{ size }} لو بتحبها أوسع",
    "fit.disclaimer": "ده مجرد استرشاد تقريبي مش مؤكد 100% — كل جسم مختلف. لو مش متأكد، كلّمنا واتساب وهنساعدك.",
    "fit.cta": "احسب",
    "fit.select": "اختار المقاس ده",
}

EN = {
    "general.error": "Something glitched. Try again.",
    "general.copied": "Link copied ✓",
    "general.whatsapp": "WhatsApp us",
    "general.loading": "One sec…",
    "sections.hero.heading": "Stitched in Cairo. Worn everywhere.",
    "sections.hero.subheading": "Heavyweight streetwear. Embroidered, never printed.",
    "sections.hero.cta": "Shop the drop",
    "sections.hero.cta2": "Make yours",
    "sections.hero.trust_1": "Free shipping over LE 2,000",
    "sections.hero.trust_2": "14-day no-drama exchange",
    "sections.hero.trust_3": "Real embroidery, not print",
    "newsletter.footer_label": "Drop alerts before anyone else, plus 10% off your first order.",
    "newsletter.button": "I'm in",
    "newsletter.success": "You're in the flock 🐧",
    "search.placeholder": "Looking for…? hoodie, tee, cap",
    "search.popular": "Everyone's searching",
    "search.no_results": "Nothing here. Try another word.",
    "wishlist.saved": "Saved ♥",
    "wishlist.removed": "Removed from saved",
    "wishlist.empty_title": "Nothing saved yet",
    "wishlist.empty_body": "Tap the heart on any piece and it lands here.",
    "collections.apply": "Show results",
    "collections.in_stock": "In stock only",
    "collections.empty": "No pieces match those filters. Loosen up a bit.",
    "products.quick_add": "Quick add",
    "products.quick_view": "Quick look",
    "products.add_to_bag": "Add to bag",
    "products.notify_me": "Tell me when it's back",
    "products.choose_size": "Pick your size",
    "products.low_stock": "Only {{ count }} left 👀",
    "products.recently_viewed": "Seen recently",
    "products.share": "Share this piece",
    "products.view_full": "Full details",
    "products.true_to_size": "Oversized cut — between sizes? Go one down",
    "products.shipping_body": "<p>Free shipping over LE 2,000. Cash on delivery anywhere in Egypt. 14-day exchange if it's unworn with tags.</p>",
    "products.fabric_body": "<p>Heavyweight 340 gsm melton cotton. Embroidered, not printed. Wash cold, inside out. Skip the dryer.</p>",
    "cart.title": "Your bag",
    "cart.added": "Added to bag",
    "cart.checkout": "Checkout",
    "cart.remove": "Remove",
    "cart.empty_title": "Your bag is empty",
    "cart.empty_body": "Nothing stitched yet. Start with the new drop.",
    "cart.start_shopping": "Let's shop",
    "cart.free_shipping_unlocked": "Free shipping unlocked 🎉",
    "cart.free_shipping_away": "{{ amount }} away from free shipping",
    "cart.free_shipping_away_html": "<strong>{{ amount }}</strong> away from free shipping",
    "cart.discount_code": "Discount code",
    "cart.discount_placeholder": "Enter your code",
    "cart.apply_discount": "Apply",
    "cart.discount_hint": "Applied at checkout.",
    "customize.subtitle": "Upload your artwork, pick a piece and colour, see it live.",
    "customize.remove": "Remove",
    "customize.front": "Front",
    "customize.back": "Back",
    "customize.notes": "Notes for the team",
    "customize.notes_placeholder": "Thread colour, exact spot, anything…",
    "customize.need_design": "Upload a design first",
    "customize.hint_3d": "Drag the design anywhere on the piece",
    "customize.step_4": "We stitch it in 3–5 days",
    "customize.reset": "Reset position",
    "customize.quantity": "How many pieces",
    "customize.sizes_title": "Size for each piece",
    "customize.piece": "Piece {{ n }}",
    "customize.min_embroidery": "Embroidery starts at 10 pieces. Print from a single piece.",
    "customize.min_embroidery_short": "Embroidery: minimum 10 pieces",
    "customize.print_note": "Print from 1 piece ✓",
    "customize.contact": "Talk to us first",
    "customize.contact_body": "Not sure about the file or the quantity? Send us the artwork on WhatsApp and we'll sort it with you.",
    "customize.per_piece": "{{ price }} / piece",
    "customize.pieces_total": "{{ count }} pieces · {{ total }}",
    "customer.account.welcome": "Hey {{ name }} 👋",
    "customer.login.title": "Sign in",
    "customer.login.create": "Create account",
    "customer.login.guest": "Continue as guest",
    "customer.register.perk_3": "Early access to drops",
    "contact.title": "Talk to us",
    "contact.success": "Got it — we reply within 24 hours.",
    "page_404.title": "Lost in the stitches",
    "page_404.body": "That page doesn't exist — the new drop does.",
    "page_404.cta": "Back to the drop",
    "home.bestsellers_eyebrow": "Best sellers",
    "home.bestsellers_heading": "What everyone's grabbing",
    "home.collections_eyebrow": "Collections",
    "home.collections_heading": "Pick your drop",
    "home.collections_customize_label": "Make yours",
    "home.collections_customize_sub": "Your art, our thread",
    "home.collections_all_label": "Everything",
    "home.campaign_body": "Forest heavyweight fleece, cream embroidery, rounded everything. Built for Cairo nights.",
    "home.campaign_primary": "Shop hoodies",
    "home.campaign_secondary": "Make yours",
    "home.campaign_note": "LIMITED RUN · FW26",
    "home.arrivals_eyebrow": "Just dropped",
    "home.arrivals_heading": "Fresh off the machine",
    "home.look_eyebrow": "The full look",
    "home.look_heading": "Whole fit, one tap",
    "home.look_body": "Tap any dot on the photo, or add straight from the list.",
    "home.prop_2_title": "Pay on delivery",
    "home.prop_2_text": "Cash when it lands, or card if you like.",
    "home.prop_3_text": "Wrong size? Swap it, no questions.",
    "home.prop_4_text": "Thread that outlives the trend.",
    "home.statement_eyebrow": "Who we are",
    "home.statement_cta": "Our story",
    "home.reviews_eyebrow": "Word on the street",
    "home.reviews_heading": "Worn & rated",
    "home.ugc_eyebrow": "Community",
    "home.ugc_heading": "Worn in the wild",
    "home.faq_eyebrow": "FAQ",
    "home.faq_heading": "Everything you need to know",
    "home.newsletter_eyebrow": "Join the flock",
    "home.newsletter_heading": "Know about drops before anyone.",
    "home.footer_tagline": "Cairo streetwear. Embroidered, not printed. Built to outlive the trend.",
    "home.announcement": "Free shipping over LE 2,000 · Pay on delivery · 14-day exchange",
    "home.mega_promo": "FW26 drop",
    "home.customize_faq_title": "Good to know",
    "home.marquee_5": "Pay on delivery",
    "bundle.title": "Buy more, pay less",
    "bundle.subtitle": "Discount applies automatically in your bag.",
    "bundle.tier": "Buy {{ count }}",
    "bundle.save": "Save {{ percent }}%",
    "bundle.each": "{{ price }} / piece",
    "bundle.add": "Add {{ count }} to bag",
    "bundle.mix": "Mix colours and sizes",
    "fit.title": "Find your size",
    "fit.subtitle": "Enter your height and weight and we'll suggest the closest size.",
    "fit.height": "Height (cm)",
    "fit.weight": "Weight (kg)",
    "fit.style": "How do you like it?",
    "fit.regular": "True to size",
    "fit.oversized": "Oversized",
    "fit.result": "You're most likely a",
    "fit.result_alt": "or {{ size }} if you like it roomier",
    "fit.disclaimer": "This is a rough guide, not a guarantee — every body is different. Not sure? WhatsApp us and we'll help.",
    "fit.cta": "Calculate",
    "fit.select": "Select this size",
}


def apply(rel, changes):
    p = ROOT / rel
    d = json.loads(p.read_text(encoding="utf-8"))
    for key, val in changes.items():
        parts = key.split(".")
        o = d
        for k in parts[:-1]:
            o = o.setdefault(k, {})
        o[parts[-1]] = val
    p.write_text(json.dumps(d, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


apply("locales/ar.json", AR)
apply("locales/en.default.json", EN)
# mirror any AR-only keys into EN so theme-check's MatchingTranslations stays clean
en = json.loads((ROOT / "locales/en.default.json").read_text(encoding="utf-8"))
ar = json.loads((ROOT / "locales/ar.json").read_text(encoding="utf-8"))


def mirror(a, e):
    for k, v in a.items():
        if isinstance(v, dict):
            mirror(v, e.setdefault(k, {}))
        elif k not in e:
            e[k] = v
mirror(ar, en)
(ROOT / "locales/en.default.json").write_text(json.dumps(en, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print("ok")
